### ISSUE TITLE
Gmail email client strips button styling - Login button appears as blue text instead of styled button

### ISSUE THREAD

**Issue by owen-rote** [owen-rote/SpaceSync-Cloud#2]
## Problem
The login button in our welcome email template displays correctly in our editor but fails to render properly in Gmail. Instead of showing as a styled blue button with white text, Gmail displays it as plain blue text without the button styling.

## Current Behavior
- **In Editor**: Button displays as intended - blue background (#4481C1), white text, rounded corners, proper padding
- **In Gmail**: Button styling is stripped - appears as blue underlined text link

## Expected Behavior
The login button should display consistently across all email clients, including Gmail, with the proper blue background and white text styling.

## Technical Details
The current button implementation uses:
```css
.button {
  display: inline-block;
  background-color: var(--color-primary-blue); /* Blue button */
  color: var(--color-white);
  padding: 12px 20px;
  text-decoration: none;
  border-radius: 5px;
  font-weight: bold;
  font-size: 14px;
}
```

## Root Cause
Gmail has limited CSS support and often strips out:
- CSS custom properties (variables like `var(--color-primary-blue)`)
- Complex CSS selectors
- Certain CSS properties in `<style>` blocks

## Recommended Solution
Implement Gmail-compatible button styling using:
1. **Inline styles** instead of CSS classes
2. **Table-based button structure** for better email client compatibility
3. **Fallback colors** instead of CSS variables
4. **MSO conditional comments** for Outlook compatibility

## Code Example
Replace the current button with:
```html
<!-- Gmail-compatible button -->
<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin: 20px 0;">
  <tr>
    <td style="border-radius: 5px; background: #4481C1;">
      <a href="https://dev.is.fun/login" target="_blank" style="background: #4481C1; border: none; font-family: Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 16px; text-decoration: none; padding: 12px 20px; color: #ffffff; display: block; border-radius: 5px;">Log In</a>
    </td>
  </tr>
</table>
```

## Testing Required
- Test across major email clients (Gmail, Outlook, Apple Mail, etc.)
- Test on both desktop and mobile versions
- Verify accessibility and screen reader compatibility
